export const SUB_REGION_SUCCESS = "SUB_REGION_SUCCESS";
export const SUB_REGION_FAILED = "SUB_REGION_FAILED";
export const SUB_REGION_PENDING = "SUB_REGION_PENDING";
export const CREATE_SUB_REGION_SUCCESS = "CREATE_SUB_REGION_SUCCESS";
export const UPDATE_SUB_REGION_SUCCESS = "UPDATE_SUB_REGION_SUCCESS";
export const DELETE_SUB_REGION_SUCCESS = "DELETE_SUB_REGION_SUCCESS";
