export const ALL_BADGE_SUCCESS = "ALL_BADGE_SUCCESS";
export const ALL_BADGE_FAILED = "ALL_BADGE_FAILED";
export const ALL_BADGE_PENDING = "ALL_BADGE_PENDING";
export const CREATE_BADGE_SUCCESS = "CREATE_BADGE_SUCCESS";
export const UPDATE_BADGE_SUCCESS = "UPDATE_BADGE_SUCCESS";
export const DELETE_BADGE_SUCCESS = "DELETE_BADGE_SUCCESS";
