export const AVATAR_START = "AVATAR_START";
export const AVATAR_CREATE_SUCCESS = "AVATAR_CREATE_SUCCESS";
export const AVATAR_GET_SUCCESS = "AVATAR_GET_SUCCESS";
export const AVATAR_EDIT_SUCCESS = "AVATAR_EDIT_SUCCESS";
export const AVATAR_DELETE_SUCCESS = "AVATAR_DELETE_SUCCESS";
export const AVATAR_FAIL = "AVATAR_FAIL";
