export const MODULE_SUCCESS = "MODULE_SUCCESS";
export const MODULE_FAILED = "MODULE_FAILED";
export const MODULE_PENDING = "MODULE_PENDING";
export const CREATE_MODULE_SUCCESS = "CREATE_MODULE_SUCCESS";
export const UPDATE_MODULE_SUCCESS = "UPDATE_MODULE_SUCCESS";
export const DELETE_MODULE_SUCCESS = "DELETE_MODULE_SUCCESS";
