export const QUIZ_SUCCESS = "QUIZ_SUCCESS";
export const QUIZ_FAILED = "QUIZ_FAILED";
export const QUIZ_PENDING = "QUIZ_PENDING";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const UPDATE_QUIZ_SUCCESS = "UPDATE_QUIZ_SUCCESS";
export const DELETE_QUIZ_SUCCESS = "DELETE_QUIZ_SUCCESS";
