export const TRAINEE_SUCCESS = "TRAINEE_SUCCESS";
export const TRAINEE_FAILED = "TRAINEE_FAILED";
export const TRAINEE_PENDING = "TRAINEE_PENDING";
export const CREATE_TRAINEE_SUCCESS = "CREATE_TRAINEE_SUCCESS";
export const UPDATE_TRAINEE_SUCCESS = "UPDATE_TRAINEE_SUCCESS";
export const DELETE_TRAINEE_SUCCESS = "DELETE_TRAINEE_SUCCESS";
