export const REGION_SUCCESS = "REGION_SUCCESS";
export const REGION_FAILED = "REGION_FAILED";
export const REGION_PENDING = "REGION_PENDING";
export const CREATE_REGION_SUCCESS = "CREATE_REGION_SUCCESS";
export const UPDATE_REGION_SUCCESS = "UPDATE_REGION_SUCCESS";
export const DELETE_REGION_SUCCESS = "DELETE_REGION_SUCCESS";
