export const COURSE_SUCCESS = "COURSE_SUCCESS";
export const COURSE_FAILED = "COURSE_FAILED";
export const COURSE_PENDING = "COURSE_PENDING";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
