export const LESSON_SUCCESS = "LESSON_SUCCESS";
export const LESSON_FAILED = "LESSON_FAILED";
export const LESSON_PENDING = "LESSON_PENDING";
export const CREATE_LESSON_SUCCESS = "CREATE_LESSON_SUCCESS";
export const UPDATE_LESSON_SUCCESS = "UPDATE_LESSON_SUCCESS";
export const DELETE_LESSON_SUCCESS = "DELETE_LESSON_SUCCESS";
