
export const ALL_PROFILE_SUCCESS = "ALL_PROFILE_SUCCESS";
export const ALL_PROFILE_FAILED = "ALL_PROFILE_FAILED";
export const ALL_PROFILE_PENDING = "ALL_PROFILE_PENDING";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
