export const TERRITORY_SUCCESS = "TERRITORY_SUCCESS";
export const TERRITORY_FAILED = "TERRITORY_FAILED";
export const TERRITORY_PENDING = "TERRITORY_PENDING";
export const CREATE_TERRITORY_SUCCESS = "CREATE_TERRITORY_SUCCESS";
export const UPDATE_TERRITORY_SUCCESS = "UPDATE_TERRITORY_SUCCESS";
export const DELETE_TERRITORY_SUCCESS = "DELETE_TERRITORY_SUCCESS";
